queue: default

pr:
  branches:
    include:
    - refs/heads/*
    exclude:
    - refs/heads/master
  paths:
   include:
   - "*"
   exclude:
   - "README.md"

steps:
- checkout: none
- script: echo hi

