set TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImV2Z3gyT1VMWFhrVWxEeE9kMVN4QzlkbGhEUSJ9.eyJuYW1laWQiOiJkZGRkZGRkZC1kZGRkLWRkZGQtZGRkZC1kZGRkZGRkZGRkZGQiLCJzY3AiOiJBY3Rpb25zUnVudGltZS5QYWNrYWdlRG93bmxvYWQiLCJJZGVudGl0eVR5cGVDbGFpbSI6IlN5c3RlbTpTZXJ2aWNlSWRlbnRpdHkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJERERERERERC1ERERELUREREQtRERERC1EREREREREREREREQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3ByaW1hcnlzaWQiOiJkZGRkZGRkZC1kZGRkLWRkZGQtZGRkZC1kZGRkZGRkZGRkZGQiLCJhdWkiOiJlMGEzZjYxNy01Njc0LTQ4M2UtYmY0YS1iMTc4M2Y2NWY3ZTUiLCJzaWQiOiIyNmI1YjhhMy1hNTQwLTRhZWQtYWRjNy0zNmZhNWE2ZTUyN2IiLCJpc3MiOiJnaDIwMzg0LmdpdGh1YnRlc3QuY29tIiwiYXVkIjoiZ2gyMDM4NC5naXRodWJ0ZXN0LmNvbSIsIm5iZiI6MTYxMTI2NzQ2MCwiZXhwIjoxNjExMjY4NjYwfQ.CQie0sMFLW6qpCLclWxb9B8jHd9zs0qd8QCK-K7xdJuT6fzj28gCv3KgIrfFwTKN50mV_uGMhOJnt96Q7qohbgzij93eT5jd67f1OZ200TaqRkJXiQDRyGoMs8omcoPGnszrhdXrogYsumDuX-ySpvgSkuBULoE5i2nSeU6lnyA75VDHF2TAhShFqs-YP5A8rC0MSutJYQeBv0Z6T8IHfVrxlScp-k8Lyzr7qvyeQJYXFvJtlSPhNpzz1fH3dBfn6rgeIVAnDLSvPxUhKIGuW6WLWPSgeurmiRPXAQxFa0IVrF1SHACrbSNMcM9hxhud0ZKOiL9og_YnqJVylZbD_RZT8Rjne9pSmGcVaxoON3uRccshMxlAAhY65ZJpvS6Ox4a_Bo8Qv9wcq2F9ub2faYwBVZxtllRuI_Y17Pj_erGsvVHRnlfRBUorMPbyYudSiatzN0zONRQz4XDyaKtB6zWO9EbI9VymPzlDjoY0fz3-yasDvu7LYD4t9aDez5UsH-DT5E2Wtd39n9x2vLLw16FVRs0WoPhGwlRyHDVhBZj8iEB_EZ6qZgGl64E5BtVNxgSyKePN5OdBCJUQrX9hoOKSfrkKycTo3OIJeTTZUQ0y7F1cFnMm4jSZTH5qotr5cpvfOt8WJO1uuT-7e_I_gUlRdbLKN0LCRxl7JzXM72s


set DOWNLOAD_URL=https://gh20384.githubtest.com/_services/pipelines/_apis/distributedtask/packagedownload/agent/win-x64/2.275.1
set PACKAGES_URL=https://gh20384.githubtest.com/_services/pipelines/_apis/distributedtask/packages

echo %DOWNLOAD_URL%
echo %TOKEN%

rem curl -H "Authorization: Bearer %TOKEN%" -o runner.zip https://gh20384.githubtest.com/_services/pipelines/_apis/distributedtask/packagedownload/agent/win-x64/2.275.1 

powershell -NonInteractive -command "$progressPreference = 'silentlyContinue' ; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -UseBasicParsing -Uri $env:DOWNLOAD_URL -Headers @{ 'Authorization' = 'Bearer ' + $env:TOKEN } -Outfile runner-from-ps.zip"
rem powershell -NonInteractive -command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -UseBasicParsing -Uri $env:PACKAGES_URL -Headers @{ 'Authorization' = 'Bearer ' + $env:TOKEN } -Outfile runner-from-ps.zip"
