name: 'Test composite'
inputs:
  context:
    default: ${{ toJSON(github.action_ref) }}
runs:
  using: composite
  steps:
  - name: dump input
    run: echo 'inputs.context=${{ inputs.context }}'
    shell: bash
  - name: using env
    env:
      JSON_ENCODED: ${{ toJSON(github.action_ref) }}
    run: echo "github.action_ref via env=${JSON_ENCODED}"
    shell: bash
  - name: in run
    run: echo 'github.action_ref directly ${{ toJSON(github.action_ref) }}'
    shell: bash
