name: Lab CI
on:
  push:
    paths:
      - .github/workflows-lab/ci.yml
jobs:
  build:
    runs-on: ubuntu-latest
    name: "   my job name 1   "
    steps:
      - run: echo hi
      - run: ping -c 10 127.0.0.1
      - run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/bbq-beets/ericsciple-test/actions/runs/${{ github.run_id }}/jobs
  test:
    runs-on: ubuntu-latest
    name: "my job name 2"
    steps:
      - run: echo hi
      - run: ping -c 10 127.0.0.1
      - run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/bbq-beets/ericsciple-test/actions/runs/${{ github.run_id }}/jobs

