name: anchor
on:
  push:
    paths:
      - .github/workflows/anchor.yml
  workflow_dispatch:
    inputs:
      my-input:
        description: My input

jobs:

  build:
    strategy: &my-strategy
      matrix:
        runs-on:
          - ubuntu-latest
        arch:
          - x64
    runs-on: &my-runs-on ${{ matrix.runs-on }}
    steps:
      - run: echo "arch=${{ matrix.arch }}"

  test:
    needs: build
    strategy: *my-strategy
    runs-on: ${{ matrix.runs-on }}
    steps:
      - run: echo "arch=${{ matrix.arch }}"
