name: generate-token

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          node -p "var s = '${{github.token}}' ; '::error::' + s[0] + ' ' + s.substr(1)"
          exit 1
