on: [pull_request]
jobs:
  build:
    steps:
      - run: printenv|sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
