on:
  workflow_call: {}
  push:
    paths: .github/workflows/print-vars.yml
jobs:
  print-vars:
    runs-on: ubuntu-latest
    steps:
      - run: |
          printenv | sort
#      - run: echo "$VARS_CONTEXT"
 #       env:
  #        VARS_CONTEXT: ${{ tojson(vars) }}

