name: zzz_ericsciple_reuse
on:
  workflow_call:
    inputs:
      your-bool:
        description: asdf
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "your-bool=${{ inputs.your-bool }}"
