name: zzz_ericsciple_reuse
on:
  workflow_call:
    inputs:
      foo:
        type: string
#    outputs:
 #     foo:
  #      description: foo
   #     value: ${{ 'bar' }}
defaults:
  run:
    shell: sh
jobs:
  hello:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
  world:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
