name: "CI"
on:
  push:
    paths: .github/workflows/test-concurrency-gates.yml
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: test-concurrency-1
      cancel-in-progress: false
    environment: test-environment-1
    steps:
      - run: echo hi
