name: Test Transitive Dependency (new)
on:
  push:
    branches: main
    paths:
      - .github/workflows/test-transitive-new.yml
jobs:
  succeed:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
  skip:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
  summary:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - succeed
      - skip
    steps:
      - run: |-
          for status in ${{ join(needs.*.result, ' ') }}
          do
            if [ "$status" != "success" ] && [ "$status" != "skipped" ]
            then
              echo "Some checks failed"
              exit 1
            fi
          done
  afterall:
    runs-on: ubuntu-latest
    needs: summary
    steps:
      - run: echo hi

